### ISSUE TITLE
Incorrect vertical alignment of icons in Safari 11 while using Bootstrap 4

### ISSUE THREAD

**Issue by kniziol** [symfony/profiler-pack#5]
**Incorrect behavior**

Take a look at vertical alignment of icons:

![invalid](https://user-images.githubusercontent.com/947620/42847568-bb93bc72-8a1c-11e8-8a76-51a891b32ccc.png)

**Correct behavior**

Icons should be aligned as shown here:

![valid](https://user-images.githubusercontent.com/947620/42847616-ceaee64c-8a1c-11e8-9d4d-0066467b2722.png)

**Versions**

- Bootstrap: v4.1.2
- Safari: 11.1.2

**Source of problem**

Property `vertical-align: middle;` of element `svg:not(:root)`:

```sass
// node_modules/bootstrap/scss/_reboot.scss

svg:not(:root) {
  overflow: hidden; // Hide the overflow in IE
  vertical-align: middle; // <------------------ Here 
}
```

**Temporarily solution**

```sass
svg:not(:root) {
  vertical-align: baseline;
}
```

**Question**

Is there better solution? :)

**Comment by fabpot** [comment]
That's already been fixed in Symfony itself.. Thanks for reporting.

**Comment by kniziol** [comment]
Which version? In Symfony 4.1.1 is not fixed.
